_wandb:
    value:
        cli_version: 0.25.0
        e:
            spa8pjg3l3hxhrm3hoagtyu6x25w30u3:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1022836600832"
                        used: "953534238720"
                email: da25m004@smail.iitm.ac.in
                executable: C:\Users\thaku\ClassRoom Assignments\DL_Assignment-1\dl_env\Scripts\python.exe
                git:
                    commit: e3ba25d0da269789d5608cc32fd74737f22b9df5
                    remote: https://github.com/AdityaThakur-DA25M004/DL_Assignment_1.1.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-b6db2ac1-5edf-4d89-f30f-11c4f0c20901
                host: Eddy87
                memory:
                    total: "16886128640"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\thaku\ClassRoom Assignments\DL_ass\src\train.py
                python: CPython 3.11.9
                root: C:\Users\thaku\ClassRoom Assignments\DL_ass
                startedAt: "2026-03-06T20:50:22.828589Z"
                writerId: spa8pjg3l3hxhrm3hoagtyu6x25w30u3
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.9
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 10
gradient_clip:
    value: 5
hidden_size:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
no_wandb:
    value: false
num_layers:
    value: 3
optimizer:
    value: adam
wandb_entity:
    value: null
wandb_project:
    value: da6401-assignment1
weight_decay:
    value: 0.0001
weight_init:
    value: xavier
