_wandb:
    value:
        cli_version: 0.25.0
        e:
            96t1dm1ymqh9j33gfhn1fe112b2fexev:
                args:
                    - -d
                    - mnist
                    - -e
                    - "50"
                    - -b
                    - "64"
                    - -l
                    - cross_entropy
                    - -o
                    - rmsprop
                    - -lr
                    - "0.0001"
                    - -wd
                    - "2e-3"
                    - -nhl
                    - "2"
                    - -sz
                    - "128"
                    - "32"
                    - -a
                    - tanh
                    - -w_i
                    - xavier
                    - --wandb_project
                    - DA6401_Assignment_1.1
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1022836600832"
                        used: "953538531328"
                email: da25m004@smail.iitm.ac.in
                executable: C:\Users\thaku\ClassRoom Assignments\DL_Assignment-1\dl_env\Scripts\python.exe
                git:
                    commit: e3ba25d0da269789d5608cc32fd74737f22b9df5
                    remote: https://github.com/AdityaThakur-DA25M004/DL_Assignment_1.1.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-b6db2ac1-5edf-4d89-f30f-11c4f0c20901
                host: Eddy87
                memory:
                    total: "16886128640"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\thaku\ClassRoom Assignments\DL_ass\src\train.py
                python: CPython 3.11.9
                root: C:\Users\thaku\ClassRoom Assignments\DL_ass
                startedAt: "2026-03-06T20:54:19.811520Z"
                writerId: 96t1dm1ymqh9j33gfhn1fe112b2fexev
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.9
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 50
gradient_clip:
    value: 5
hidden_size:
    value:
        - 128
        - 32
learning_rate:
    value: 0.0001
loss:
    value: cross_entropy
no_wandb:
    value: false
num_layers:
    value: 2
optimizer:
    value: rmsprop
wandb_entity:
    value: null
wandb_project:
    value: DA6401_Assignment_1.1
weight_decay:
    value: 0.002
weight_init:
    value: xavier
